// G-Mura · Productos + Variantes — datos mock

const PROD_LIST = [
  {
    id: 'cm-basica',
    name: 'Camiseta Básica',
    brand: 'G-Mura Essentials',
    category: 'Camisetas',
    description: 'Algodón 100% peinado, corte regular. Hecha en Medellín.',
    img: 'linear-gradient(135deg, #fafaf7 0%, #ebebe4 100%)',
    swatch: '#f5f5f0',
    basePrice: 35000,
    variants: [
      { id: 'v1', size: 'XS', color: 'Blanco', colorHex: '#f5f5f0', sku: 'CM-BAS-XS-BLK', price: 35000, stock: 4, status: 'active' },
      { id: 'v2', size: 'S',  color: 'Blanco', colorHex: '#f5f5f0', sku: 'CM-BAS-S-BLK',  price: 35000, stock: 8, status: 'active' },
      { id: 'v3', size: 'M',  color: 'Blanco', colorHex: '#f5f5f0', sku: 'CM-BAS-M-BLK',  price: 35000, stock: 5, status: 'active' },
      { id: 'v4', size: 'L',  color: 'Blanco', colorHex: '#f5f5f0', sku: 'CM-BAS-L-BLK',  price: 35000, stock: 0, status: 'active' },
      { id: 'v5', size: 'XS', color: 'Negro',  colorHex: '#1a1a1a', sku: 'CM-BAS-XS-NGR', price: 35000, stock: 6, status: 'active' },
      { id: 'v6', size: 'S',  color: 'Negro',  colorHex: '#1a1a1a', sku: 'CM-BAS-S-NGR',  price: 35000, stock: 7, status: 'active' },
      { id: 'v7', size: 'M',  color: 'Negro',  colorHex: '#1a1a1a', sku: 'CM-BAS-M-NGR',  price: 35000, stock: 2, status: 'active' },
      { id: 'v8', size: 'L',  color: 'Negro',  colorHex: '#1a1a1a', sku: 'CM-BAS-L-NGR',  price: 35000, stock: 3, status: 'active' },
    ],
  },
  {
    id: 'jn-slim',
    name: 'Jeans Slim Fit',
    brand: 'Denim Co.',
    category: 'Pantalones',
    description: 'Denim 12oz con elastano. Lavado oscuro y costuras reforzadas.',
    img: 'linear-gradient(135deg, #2a2a2e 0%, #131316 100%)',
    swatch: '#1a1a1a',
    basePrice: 89000,
    variants: [
      { id: 'v1', size: '28', color: 'Negro',     colorHex: '#1a1a1a', sku: 'JN-SLM-28-NGR', price: 89000, stock: 2, status: 'active' },
      { id: 'v2', size: '30', color: 'Negro',     colorHex: '#1a1a1a', sku: 'JN-SLM-30-NGR', price: 89000, stock: 6, status: 'active' },
      { id: 'v3', size: '32', color: 'Negro',     colorHex: '#1a1a1a', sku: 'JN-SLM-32-NGR', price: 89000, stock: 0, status: 'active' },
      { id: 'v4', size: '28', color: 'Azul ind.', colorHex: '#2d3748', sku: 'JN-SLM-28-AZL', price: 89000, stock: 4, status: 'active' },
      { id: 'v5', size: '30', color: 'Azul ind.', colorHex: '#2d3748', sku: 'JN-SLM-30-AZL', price: 89000, stock: 0, status: 'active' },
      { id: 'v6', size: '32', color: 'Azul ind.', colorHex: '#2d3748', sku: 'JN-SLM-32-AZL', price: 89000, stock: 1, status: 'active' },
    ],
  },
  {
    id: 'vs-floral',
    name: 'Vestido Floral',
    brand: 'Bloom Studio',
    category: 'Vestidos',
    description: 'Largo midi, manga corta, estampado exclusivo edición primavera.',
    img: 'linear-gradient(135deg, #f4e4ed 0%, #d9b8cc 60%, #8b6f7d 100%)',
    swatch: '#e8d5e0',
    basePrice: 65000,
    variants: [
      { id: 'v1', size: 'XS', color: 'Rosa polvo', colorHex: '#e8d5e0', sku: 'VS-FLR-XS-RSA', price: 65000, stock: 3, status: 'active' },
      { id: 'v2', size: 'S',  color: 'Rosa polvo', colorHex: '#e8d5e0', sku: 'VS-FLR-S-RSA',  price: 65000, stock: 1, status: 'active' },
      { id: 'v3', size: 'M',  color: 'Rosa polvo', colorHex: '#e8d5e0', sku: 'VS-FLR-M-RSA',  price: 65000, stock: 2, status: 'active' },
      { id: 'v4', size: 'L',  color: 'Rosa polvo', colorHex: '#e8d5e0', sku: 'VS-FLR-L-RSA',  price: 65000, stock: 4, status: 'active' },
    ],
  },
  {
    id: 'cn-cafe',
    name: 'Cinturón Café',
    brand: 'G-Mura Leather',
    category: 'Accesorios',
    description: 'Cuero vegetal curtido a mano. Hebilla de bronce envejecido.',
    img: 'linear-gradient(135deg, #8b5a2b 0%, #5c3a1c 100%)',
    swatch: '#6b4423',
    basePrice: 28000,
    variants: [
      { id: 'v1', size: 'Única', color: 'Café', colorHex: '#6b4423', sku: 'CN-CAF-UN-CFE', price: 28000, stock: 12, status: 'active' },
      { id: 'v2', size: 'Única', color: 'Negro', colorHex: '#1a1a1a', sku: 'CN-CAF-UN-NGR', price: 28000, stock: 8, status: 'active' },
    ],
  },
  {
    id: 'cm-lino',
    name: 'Camisa Lino Crudo',
    brand: 'Atelier Norte',
    category: 'Camisetas',
    description: 'Lino europeo, botones de coco. Cae como cae.',
    img: 'linear-gradient(135deg, #f0e6d2 0%, #d4c5a3 100%)',
    swatch: '#e8dcc4',
    basePrice: 78000,
    variants: [
      { id: 'v1', size: 'S', color: 'Crudo', colorHex: '#e8dcc4', sku: 'CM-LIN-S-CRD', price: 78000, stock: 4, status: 'active' },
      { id: 'v2', size: 'M', color: 'Crudo', colorHex: '#e8dcc4', sku: 'CM-LIN-M-CRD', price: 78000, stock: 7, status: 'active' },
      { id: 'v3', size: 'L', color: 'Crudo', colorHex: '#e8dcc4', sku: 'CM-LIN-L-CRD', price: 78000, stock: 3, status: 'active' },
    ],
  },
  {
    id: 'sn-blanco',
    name: 'Sneaker Blanco',
    brand: 'Walk Co.',
    category: 'Calzado',
    description: 'Cuero italiano, suela de caucho. Confortables todo el día.',
    img: 'linear-gradient(135deg, #ffffff 0%, #e8e8e8 100%)',
    swatch: '#fafafa',
    basePrice: 145000,
    variants: [
      { id: 'v1', size: '37', color: 'Blanco', colorHex: '#fafafa', sku: 'SN-BLN-37-BLK', price: 145000, stock: 3, status: 'active' },
      { id: 'v2', size: '38', color: 'Blanco', colorHex: '#fafafa', sku: 'SN-BLN-38-BLK', price: 145000, stock: 4, status: 'active' },
      { id: 'v3', size: '39', color: 'Blanco', colorHex: '#fafafa', sku: 'SN-BLN-39-BLK', price: 145000, stock: 5, status: 'active' },
      { id: 'v4', size: '40', color: 'Blanco', colorHex: '#fafafa', sku: 'SN-BLN-40-BLK', price: 145000, stock: 2, status: 'active' },
    ],
  },
];

const stockState = (n) => n === 0 ? 'out' : (n <= 2 ? 'low' : 'ok');

Object.assign(window, { PROD_LIST, stockState });
